import type React from 'react';

/** Shared compact admin action buttons — small, responsive, dense UI. */
export const adminBtn = {
  primary: {
    border: 'none',
    borderRadius: 6,
    padding: '5px 10px',
    minHeight: 28,
    background: 'var(--movr-gradient)',
    color: 'var(--brand-white)',
    fontWeight: 700,
    fontSize: 12,
    lineHeight: 1.2,
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    flexShrink: 0,
    boxSizing: 'border-box',
  } as React.CSSProperties,

  secondary: {
    border: '1px solid var(--border)',
    borderRadius: 6,
    padding: '5px 10px',
    minHeight: 28,
    background: 'var(--surface-elevated)',
    color: 'var(--text-primary)',
    fontWeight: 600,
    fontSize: 12,
    lineHeight: 1.2,
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    flexShrink: 0,
    boxSizing: 'border-box',
  } as React.CSSProperties,

  /** Inline list actions (Assign, Approve, etc.) */
  compact: {
    border: 'none',
    borderRadius: 6,
    padding: '4px 8px',
    minHeight: 26,
    background: 'var(--movr-gradient)',
    color: '#fff',
    fontWeight: 700,
    fontSize: 11,
    lineHeight: 1.2,
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    flexShrink: 0,
    boxSizing: 'border-box',
  } as React.CSSProperties,

  danger: {
    border: 'none',
    borderRadius: 6,
    padding: '5px 10px',
    minHeight: 28,
    background: 'var(--error, #ef4444)',
    color: '#fff',
    fontWeight: 700,
    fontSize: 12,
    lineHeight: 1.2,
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    flexShrink: 0,
    boxSizing: 'border-box',
  } as React.CSSProperties,

  /** Soft outline danger (Suspend, Reject) */
  dangerSoft: {
    border: '1px solid rgba(239,68,68,0.5)',
    borderRadius: 6,
    padding: '5px 10px',
    minHeight: 28,
    background: 'rgba(239,68,68,0.15)',
    color: '#f87171',
    fontWeight: 700,
    fontSize: 12,
    lineHeight: 1.2,
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    flexShrink: 0,
    boxSizing: 'border-box',
  } as React.CSSProperties,

  /** Soft outline success (Approve) */
  successSoft: {
    border: '1px solid rgba(34,197,94,0.5)',
    borderRadius: 6,
    padding: '5px 10px',
    minHeight: 28,
    background: 'rgba(34,197,94,0.15)',
    color: '#4ade80',
    fontWeight: 700,
    fontSize: 12,
    lineHeight: 1.2,
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    flexShrink: 0,
    boxSizing: 'border-box',
  } as React.CSSProperties,

  ghost: {
    border: '1px solid var(--border)',
    borderRadius: 6,
    padding: '4px 8px',
    minHeight: 26,
    background: 'transparent',
    color: 'var(--text-secondary)',
    fontWeight: 600,
    fontSize: 11,
    lineHeight: 1.2,
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    flexShrink: 0,
    boxSizing: 'border-box',
  } as React.CSSProperties,

  /** Full-width form submit — still compact height */
  block: {
    border: 'none',
    borderRadius: 8,
    padding: '8px 12px',
    minHeight: 34,
    width: '100%',
    background: 'var(--movr-gradient)',
    color: 'var(--brand-white)',
    fontWeight: 700,
    fontSize: 13,
    lineHeight: 1.2,
    cursor: 'pointer',
    boxSizing: 'border-box',
  } as React.CSSProperties,
};
